
#   ────────────────────────────────────────────────────────────────────────────────────────────────────────────
#   ─────────██████─██████████████─██████████████─██████████████─██████████████─██████████████─██████──████████─
#   ─────────██░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░░░██─
#   ─────────██░░██─██░░██████████─██████░░██████─██░░██████░░██─██░░██████░░██─██░░██████████─██░░██──██░░████─
#   ─────────██░░██─██░░██─────────────██░░██─────██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██───
#   ─────────██░░██─██░░██████████─────██░░██─────██░░██████░░██─██░░██████░░██─██░░██─────────██░░██████░░██───
#   ─────────██░░██─██░░░░░░░░░░██─────██░░██─────██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░██───
#   ─██████──██░░██─██░░██████████─────██░░██─────██░░██████████─██░░██████░░██─██░░██─────────██░░██████░░██───
#   ─██░░██──██░░██─██░░██─────────────██░░██─────██░░██─────────██░░██──██░░██─██░░██─────────██░░██──██░░██───
#   ─██░░██████░░██─██░░██████████─────██░░██─────██░░██─────────██░░██──██░░██─██░░██████████─██░░██──██░░████─
#   ─██░░░░░░░░░░██─██░░░░░░░░░░██─────██░░██─────██░░██─────────██░░██──██░░██─██░░░░░░░░░░██─██░░██──██░░░░██─
#   ─██████████████─██████████████─────██████─────██████─────────██████──██████─██████████████─██████──████████─
#   ──────────────────────────────────────────────────────────────────────────────────────────────────────────── 

#-----------------------------------------------#

# The custom model data for the Jetpack and fuel.

jetpack-model-data: 10037
fuel-model-data: 10038


#-----------------------------------------------#

# Fuel consumption

fuel-consumption-rate: 2 # = 1 fuel every 2 seconds.


#-----------------------------------------------#

# Jetpack Movement

jetpack-lift-force: 0.1
jetpack-horizontal-speed: 0.08

#-----------------------------------------------#

#  Fall damage reduction in %
#
#  0%  Reduction: Survivable up to 11 blocks
#  10% Reduction: Survivable up to 12 blocks
#  20% Reduction: Survivable up to 13 blocks
#  30% Reduction: Survivable up to 15 blocks
#  40% Reduction: Survivable up to 17 blocks
#  50% Reduction: Survivable up to 21 blocks
#  60% Reduction and above: Survivable up to 23 blocks

fall-damage-reduction: 75

#-----------------------------------------------#

# Action-bar messages
fuel-messages:
  normal-fuel: "&a&lRemaining Fuel: &2{fuel}"
  low-fuel: "&c&lLow Fuel: &4{fuel}"

#-----------------------------------------------#